### ISSUE TITLE
M1: Send an email to client to submit meeting minutes and ask questions

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#11]
1. Task Description: Send meeting minutes and ask questions to client after the first client meeting
2. Task Goals: To update and verify content discussed during meeting with client, and clarify doubts
3. Success or completion criteria: Client replies with email containing answers to follow-up questions
4. Allocated Time: 10 Hours.
5. Start Date: 12/09/23
6. End Date: 14/09/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: Medium

**Comment by tjl081** [comment]
1. Detail: Send meeting minutes and ask questions to client after the first client meeting
2. Committed to repo: No
3. How does it affect success criteria: Ensure that the documented meeting minutes are accurate, and clarifying doubts with the client reinforces our understanding of the desired final product
4. Start Date: 12/09/23
5. End Date: 14/09/23

Contributed by Jia Liang
