### ISSUE TITLE
1.3.2 Related Background Literature

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#12]
1. Task Description: Research on relevant background literature
2. Task Goals: Complete Use Case Diagrams for Milestone 1.
3. Success or completion criteria: Provide insightful research material that provides a better understanding to the project
4. Allocated Time: 4 Hours
5. Start Date: 08/09/23
6. End Date: 09/09/23
7. Task Owner: Andersen
8. Status: Completed
9. Priority: Medium

**Comment by Littlesens** [comment]
1. Detail: Research on relevant background literature
2. Committed to repo: No
3. How does it affect success criteria: Completes the background literature section
4. Start Date: 08/09/23
5. End Date: 09/09/23

Contributed by: Andersen
