### ISSUE TITLE
M1: Draft out second email for client

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#13]
Draft out questions that we need to ask the client

Goal: Draft out second email to further ask questions to client
Success criteria: Email sent to the client
Start Date: 14 September 2023
End Date: 23 September 2023
Owner: Tan Jia Liang
Status: In Progress

**Comment by tjl081** [comment]
1. Detail: Email sent to the client on Sunday 11:42PM
2. Has the work been committed?: No
3. How does it affect success or completion criteria: Success criteria has been fulfilled
4. Start Date: 16/09/23
5. End Date: 17/09/23 

Contributed by: Jia Liang
