### ISSUE TITLE
1.4.3: Functional Requirements

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#15]
1. Goal: Write out functional requirements for the M1 report
2. Success criteria: Functional requirements are to be written in the M1 Report
3. Allocated Time: 3 Business Days (8 hours each day)
4. Start Date:  10/09/23
5. End Date: 14/09/23
6. Owner: Chua Tian Le
7. Status: Completed
8. Priority: High

**Comment by ctianle** [comment]
1. Detail: Identifying the functional requirements required for this project
2. Committed to repo: No
3. How does it affect success criteria: Helps to identify to the small breakdown of each functional requirements that we need
4. Start Date: 10/09/23
5. End Date: 14/09/23

Contributed by Jia Liang, Tian Le & Andersen
