### ISSUE TITLE
1.4.4: Non-functional Requirements

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#16]
1. Task Goal: To identify and list down the non-functional requirements
2. Task Goals: Non-functional requirements to be in report
3. Success or completion criteria: Non-functional Requirements are to be indicated in the M1 report.
4. Allocated Time: 24 hours.
5. Start Date: 11/09/23
6. End Date: 14/09/23
7. Task Owner: Tian Le
8. Status: Done
9. Priority: High

**Comment by frostsg** [comment]
1. Detail: Added description about non-functional requirments
2. Committed to repo: No
3. How does it affect success criteria: It helps to identify non-functional requirements that our project requires such as being user friendly, and supporting multiple languages
4. Start Date: 11/09/23
5. End Date: 14/09/23

Contributed by Tian Le
