### ISSUE TITLE
1.5.2: Use Case Descriptions

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#18]
1. Task Description: Correctly understand the use cases and accurately depict it in use case description
2. Task Goals: Complete Use Case Description for Milestone 1.
3. Success or completion criteria: Identifying all the necessary use cases
4. Allocated Time: 20 Hours.
5. Start Date: 14/09/23
6. End Date: 18/09/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
1. Detail: Accurately write the description for use case.
2. Committed to repo: No
3. How does it affect success criteria: Helps to identify the correct description for the use cases we have
4. Start Date: 14/09/23
5. End Date: 18/09/23


Contributed: Tian Le & Jia Liang
