### ISSUE TITLE
1.83: Gantt Chart

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#19]
Goal: Create a Gantt Chart
Success criteria: Complete a Gantt Chart with all milestones recorded
Start Date: 21/09/23
End Date: 23/09/23
Owner: Soon Leung, Isaac
Status: Done

**Comment by frostsg** [comment]
1. Detail: A Gantt Chart with all the details has been created 
2. Committed to repo: No
3. How does it affect success criteria: Success Criteria fulfilled
4. Start Date: 21/09/23
5. End Date: 23/09/23

Contributed by: Isaac
