### ISSUE TITLE
1.4.2: User Interface Requirement

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#22]
1. Task Description: Identifying the User Interface Requirements
3. Task Goals: To have a clear understanding of the User Interface Requirements
4. Success or completion criteria: Identifying all the required User Interface Requirements
5. Allocated Time: 10 Hours.
6. Start Date: 10/09/23
7. End Date: 14/09/23
8. Task Owner: Andersen
9. Status: Completed
10. Priority: Medium

**Comment by Littlesens** [comment]
-

**Comment by ctianle** [comment]
1. Detail: Identifying the User Interface Requirements
2. Committed to repo: No
3. How does it affect success criteria: Helps to identity the User Interface Requirements we need.
4. Start Date: 10/09/23
5. End Date: 14/09/23

Contributed by: Andersen
