### ISSUE TITLE
1.4.1: Project Requirement Elicitation Methods

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#23]
1. Task Description: Explain the methods used to gather requirements
2. Task Goals: To mention the methods we used to obtain the different client requirements
3. Success or completion criteria: Identifying all the methods used
4. Allocated Time: 10 Hours.
5. Start Date: 10/09/23
6. End Date: 14/09/23
7. Task Owner: Andersen
8. Status: Completed
9. Priority: Medium

**Comment by Littlesens** [comment]
1. Detail: Refers to the collation and analysis of client response as well as some background reading into our project topic
2. Committed to repo: No
3. How does it affect success criteria: Completing this section ensures accurate, efficient project execution and strengthens client relationships.
4. Start Date: 08/09/23
5. End Date: 09/09/23

Contributed by: Andersen
