### ISSUE TITLE
M1: Activity Diagram

### ISSUE THREAD

**Issue by Littlesens** [frostsg/inf2001-p11-2#25]
Goal: Create Activity Diagram
Success criteria: Activity Diagram done
Start Date: 19 September 2023
End Date: 19 September 2023
Owner: Tan Jia Liang
Status: Completed

**Comment by tjl081** [comment]
Completed, contributions from everyone

**Comment by ctianle** [comment]
1. Detail: Enable us to picture and dictate the flow of how certain each case description runs in the project
2. Committed to repo: No
3. How does it affect success criteria: Helps to organise and understand the requirements
4. Start Date: 11/09/23
5. End Date: 14/09/23

Contributed by: Jia Liang, Tian Le, Andersen, Kenrick, Isaac
