### ISSUE TITLE
1.9: Data Dictionary

### ISSUE THREAD

**Issue by Littlesens** [frostsg/inf2001-p11-2#28]
Goal: Update the Data dictionary section
Success criteria: Layout the definition of terms used in this document
Start Date: 22 September 2023
End Date: 23 September 2023
Owner: Yeo Qing You, Kenrick
Status: In Progress

**Comment by Krackern** [comment]
i. Detail: Various terms such as System and IT Administrator used in the M1 report have been stated and defined in the Data Dictionary Section
ii. Committed to repo: No
iii. How does it affect success criteria: It defines terms used in the M1 Report
iv. Start Date: 22/09/23
v. End Date: 23/09/23
