### ISSUE TITLE
M1: Choice of Methodology

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#29]
Goal: Choose Methodology
Success criteria: Project Management Methoology chosen (Waterfall/Agile).
Start Date: 19 September 2023
End Date: 19 September 2023
Owner: Isaac
Status: Completed

**Comment by Krackern** [comment]
.

**Comment by frostsg** [comment]
i. Detail: Waterfall SDLC has been chosen and agreed upon by every team member with reasonable justification.
ii. Committed to repo: No
iii. How does it affect success criteria: The Choice of Methodology part has been justified and written down.
iv. Start Date: 19/09/23
v. End Date: 19/09/23

Contributed by Isaac
