### ISSUE TITLE
1.8.1: Team Management

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#31]
Goal: Complete Team Management
Success criteria: Completed Team Management under Project Management
Start Date: 21 September 2023
End Date: 23 September 2023
Owner: Yeo Qing You, Kenrick
Status: In Progress

**Comment by Krackern** [comment]
i. Detail: Added descriptions of Team Roles and Channels that were used for meetings and communications in the M1 report
ii. Committed to repo: No
iii. How does it affect success criteria: It completes the Team Management portion
iv. Start Date: 21/09/23
v. End Date: 22/09/23

Contributed by: Kenrick
