### ISSUE TITLE
1.8.2: Work Breakdown Chart

### ISSUE THREAD

**Issue by Littlesens** [frostsg/inf2001-p11-2#32]
Goal: To complete the Work Breakdown Chart
Success criteria: Complete the Work Breakdown Chart
Start Date: 21/09/23
End Date: 23/09/23
Owner: Soon Leung Isaac
Status: Done

**Comment by frostsg** [comment]
1. Detail: WBC has been added into the report
2. Committed to repo: No
3. How does it affect success criteria: Success Criteria has been fulfilled
4. Start Date: 21/09/23
5. End Date: 22/09/23
6. Task Completed


Contributed by: Kenrick
