### ISSUE TITLE
M1: Background Reading

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#33]
Goal: To complete Background Reading
Success criteria: Complete Background Reading
Start Date: 08/09/23
End Date: 09/09/23
Owner: Andersen Tan
Status: Completed

**Comment by Krackern** [comment]
1. Detail: background reading about the workload management system and pharmacy shop has been completed.
2. Committed to repo: No
3. How does it affect success criteria: Success criteria has been fulfilled
4. Start Date: 08/09/23
5. End Date: 09/09/23

Contributed by: Andersen
