### ISSUE TITLE
M1: Final update to use case diagram

### ISSUE THREAD

**Issue by Littlesens** [frostsg/inf2001-p11-2#34]
1. Task Description: Final update to use case diagram
2. Task Goals: To finalise activity diagram design
3. Success or completion criteria: Activity diagram design accepted by team
4. Allocated Time: 10 Hours.
5. Start Date: 19/09/23
6. End Date: 19/09/23
7. Task Owner: Jia Liang
8. Status: Done
9. Priority: Low

**Comment by tjl081** [comment]
1. Detail: Final update to use case diagram
2. Committed to repo: No
3. How does it affect success criteria: Finalise use case diagram to be included to M1 report.
4. Start Date: 19/09/23
5. End Date: 19/09/23
