### ISSUE TITLE
1.3.1: Product Scope

### ISSUE THREAD

**Issue by Krackern** [frostsg/inf2001-p11-2#36]
1. Task Description: Draft out the Product Scope in the M1 Report
2. Task Goals: Complete Product Scope
3. Success or completion criteria: Complete the scope of the product
4. Allocated Time: 2 Hours.
5. Start Date: 08/09/23
6. End Date: 09/09/23
7. Task Owner: Andersen
8. Status: Completed
9. Priority: Medium

**Comment by Littlesens** [comment]
1. Detail: Describe what the high-level overview of the project is 
2. Committed to repo: No
3. How does it affect success criteria: Point of reference to what our product should encompass
4. Start Date: 08/09/23
5. End Date: 09/09/23

Contributed by: Andersen
