### ISSUE TITLE
1.3.3 Intended Audience and Document

### ISSUE THREAD

**Issue by Littlesens** [frostsg/inf2001-p11-2#37]
1. Task Description: Create an Activity Diagram
2. Task Goals: To complete the intended audience and document portion of the report for M1
3. Success or completion criteria: Complete respective sections in report
4. Allocated Time: 4 hours
5. Start Date:  08/09/23
6. End Date:  09/09/23
7. Task Owner: Soon Leung Isaac
8. Status: Completed
9. Priority: High

**Comment by frostsg** [comment]
1. Detail: Intended Audience and Document
2. Committed to repo: No
3. How does it affect success criteria: Contribute to completion of M1 report
4. Start Date: 08/09/23
5. End Date: 08/09/23

Contributed by: Isaac
