### ISSUE TITLE
1.3.4 References and Acknowledgements

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#38]
1. Task Description: References and Acknowledgements
2. Task Goals: Complete the References and Acknowledgements portion of the M1 Report
3. Success or completion criteria: Respective sections completed in M1 report
4. Allocated Time: 24 hours
5. Start Date: 08/09/2023
6. End Date: 09/09/2023
7. Task Owner: Andersen Tan
8. Status: Completed
9. Priority: High

**Comment by Littlesens** [comment]
1. Detail: Indicate any references that were used to assist in the project
2. Committed to repo: No
3. How does it affect success criteria: Help us better understand the users' needs
4. Start Date: 08/09/23
5. End Date: 09/09/23

Contributed by: Andersen
