### ISSUE TITLE
1.3.5 Product Overview

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#42]
1. Task Description: Correctly understand their use case and depict the use case diagram
2. Task Goals: CompleteProduct Overview for Milestone 1 Report
3. Success or completion criteria: Description for Product Overview has been written
4. Allocated Time: 3 Hours.
5. Start Date: 09/09/23
6. End Date: 10/09/23
7. Task Owner: Yeo Qing You, Kenrick
8. Status: Completed
9. Priority: Medium

**Comment by Krackern** [comment]
i.  Detail: Added description about how the product interacts with the environment in the Milestone 1 Report
ii. Committed to repo: No
iii. How does it affect success criteria: It helps to fulfill success criteria
iv. Start Date: 09/09/23
v.  End Date: 09/09/23

Contributed by: Kenrick

**Comment by Krackern** [comment]
i. Detail: Added System's Architecture diagram in the Product Overview section in the M1 Report
ii. Committed to repo: No
iii. How does it affect success criteria: It fulfills success criteria
iv. Start Date: 10/09/23
v. End Date: 10/09/23

Contributed by: Kenrick
