### ISSUE TITLE
1.3.6 Product Functionality

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#43]
1. Task Description: Set Product Functionality Requirements for M1 Report
2. Task Goals: Determine list of product functionalities for proposed project
3. Success or completion criteria: Product functionalities all decided and agreed upon by team
4. Allocated Time: 10 Hours.
5. Start Date: 9/09/23
6. End Date: 10/09/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
1. Detail: Clarified and standardised all product functionality required for this project.
2. Committed to repo: No
3. How does it affect success criteria: It ensures we have clear understanding of client's requirement
4. Start Date: 09/09/23
5. End Date: 10/09/23

Contributed by: Jia Liang, Tian Le & Andersen
