### ISSUE TITLE
M1: Assumptions and Dependencies

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#44]
1. Task Description: Correctly identify the assumptions and dependencies
2. Task Goals: Write assumptions that the team is required to make and dependencies that the team is planning to use
3. Success or completion criteria: Identifying all assumptions and dependencies
4. Allocated Time: 10 Hours.
5. Start Date: 09/09/23
6. End Date: 10/09/23
7. Task Owner: Yeo Qing You, Kenrick
8. Status: Completed
9. Priority: Medium

**Comment by Krackern** [comment]
i. Detail: Added assumptions in the section
ii. Committed to repo: No
iii. How does it affect success criteria: It fulfills success criteria
iv. Start Date: 09/09/23
v. End Date: 09/09/23

Contributed by: Kenrick

**Comment by Krackern** [comment]
i. Detail: Added dependencies in the section
ii. Committed to repo: No
iii. How does it affect success criteria: It fulfills success criteria
iv. Start Date: 10/09/23
v. End Date: 10/09/23

Contributed by: Kenrick
