### ISSUE TITLE
2.1.1 Milestone 1 Review

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#47]
1. Task Description: To review the feedback given for M1.
2. Task Goals: To generate takeaways and objectives based on feedback given.
3. Success or completion criteria: To derive objectives and Room for Improvement based on feedback given for M1 Report.
4. Allocated Time: 1 Working Day (3 Hours)
5. Start Date: 27/09/23
6. End Date: 28/09/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Identifying where we went wrong
Committed to repo: No
How does it affect success criteria: Helps us to identify where we can improve on
Start Date: 16/10/23
End Date: 16/10/23
Contributed by Jia Liang, Tian Le, Isaac, Kendrick & Andersen
