### ISSUE TITLE
2.1.2 Updated Use Cases

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#49]
1. Task Description: To update the use cases according to feedback given from M1 Report
2. Task Goals: To refine the use cases.
3. Success or completion criteria: The updated use cases are approved by everyone.
4. Allocated Time: 1 Working Day (8 Hours)
5. Start Date: 29/09/23
6. End Date: 30/09/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Clarified all the updated use cases.
Committed to repo: No
How does it affect success criteria: Helps us determine the correct updated uses cases for m2.
Start Date: 16/10/23
End Date: 17/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kendrick
