### ISSUE TITLE
1.6.2: Estimation of Size

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#5]
1. Task Description: Estimation of size
2. Task Goals: To calculate software estimation hours
3. Success or completion criteria: Calculate Software Estimation 
4. Allocated Time: 8 hours
5. Start Date: 15/09/23
6. End Date: 16/09/23
7. Task Owner: Chua Tian Le
8. Status: Completed
9. Priority: High

**Comment by tjl081** [comment]
1. Detail: Setup an Appointment With the Client
2. Committed to repo: No
3. How does it affect success criteria: Deriving the estimated amount of time to complete the project gives the team a timeframe to follow
4. Start Date: 15/09/23
5. End Date: 16/09/23
