### ISSUE TITLE
2.1.3 Updated Use Case Model

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#50]
1. Task Description: Update the use case model with feedback given from M1 Review.
2. Task Goals: Refine the use case model.
3. Success or completion criteria: To have a refined use case model with everyone's approval.
4. Allocated Time: 1 Working Day (8 Hours)
5. Start Date: 29/09/23
6. End Date: 30/09/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Update the use case model with newer information
Committed to repo: No
How does it affect success criteria: Clarifies and updates the use case model with more accurate information
Start Date: 17/10/23
End Date: 18/10/23
Contributed by Jia Liang, Tian Le, Isaac, Kendrick & Andersen
