### ISSUE TITLE
2.1.4 Updated Use Case Description

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#51]
1. Task Description: To update the use case descriptions based on the M1 review.
2. Task Goals: To refine the use case descriptions.
3. Success or completion criteria: 
4. Allocated Time: 1 Working Day (8 Hours)
5. Start Date: 29/09/23
6. End Date: 30/09/23
7. Task Owner: Andersen
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Update the use case description with more and newer information
Committed to repo: No
How does it affect success criteria: Updates use case description by adding more transaction and making it more accurate
Start Date: 18/10/23
End Date: 19/10/23
Contributed by Jia Liang, Tian Le, Isaac, Kenrick & Andersen
