### ISSUE TITLE
2.2.2 Create Component Diagram

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#53]
1. Task Description: To create the component diagram.
2. Task Goals: To create 
3. Success or completion criteria: To have a component diagram that is acceptable to the team.
4. Allocated Time: 12 Working Days (96 Hours)
5. Start Date: 01/10/23
6. End Date: 13/10/23
7. Task Owner: Kenrick
8. Status: In Progress
9. Priority: High

**Comment by frostsg** [comment]
i. Detail: A draft of the component diagram is created
ii. Committed to repo: no
iii. How does it affect success criteria: A draft can now be presented to the team for vetting and edits. 
iv. Start Date: 17/10/23
v. End Date: 20/10/23

Contributed by: Isaac, Andersen and Kenrick

**Comment by Littlesens** [comment]
Detail: Clarified component diagrams with prof indriyani
Committed to repo: No
How does it affect success criteria: Helps us determine how we should structure our component diagram
Start Date: 23/10/23
End Date: 23/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick

Reason for overrun: Other projects and assignments to complete

**Comment by Littlesens** [comment]
Detail: Clarified component diagrams with prof eric
Committed to repo: No
How does it affect success criteria: Helps us determine how we should structure our component diagram
Start Date: 24/10/23
End Date: 24/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick

Reason for overrun: Other projects and assignments to complete

**Comment by Krackern** [comment]
Detail: Completed component diagrams
Committed to repo: No
How does it affect success criteria: It fulfils success criteria
Start Date: 25/10/23
End Date: 25/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick

Reason for overrun: Other projects and assignments to complete
