### ISSUE TITLE
2.2.3 Create Class Diagram

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#54]
1. Task Description: To create a class diagram. 
2. Task Goals: To create a class 
3. Success or completion criteria: 
4. Allocated Time: 12 Working Days (96 Hours)
5. Start Date: 01/10/23
6. End Date: 13/10/23
7. Task Owner: Kenrick
8. Status: Completed
9. Priority: Medium

**Comment by ctianle** [comment]
1. Detail: Identify important class diagram and start off the diagram
2. Committed to repo: No
3. How does it affect success criteria: Identifying the important baseline for the class diagram
4. Start Date: 16/10/23
5. End Date: 16/10/23
6. Contributed: Tian Le, Jialiang, Andersen & Isaac

**Comment by ctianle** [comment]
i. Detail: Finishing off class diagram and touching up the furnishings.
ii. Committed to repo: No
iii. How does it affect success criteria: Helps to finish up class diagram
iv. Start Date: 17/10/23
v. End Date: 23/10/23
vi. Contributed: Tian Le, Jialiang, Andersen, Isaac, Kenrick
