### ISSUE TITLE
2.2.4 Create Sequence Diagrams

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#55]
1. Task Description: To create the sequence diagrams
2. Task Goals: To show the sequence of the application via diagrams.
3. Success or completion criteria: Sequence diagrams must be drawn completely and accepted by everyone in the team.
4. Allocated Time: 12 Working Days (96 Hours)
5. Start Date: 01/10/23
6. End Date: 13/10/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: Medium

**Comment by ctianle** [comment]
Detail: Identify prominent use case description and start to draw the sequence diagram
Committed to repo: No
How does it affect success criteria: Helps to identify what we should focus on for sequence diagram 
Start Date: 18/10/23
End Date: 20/10/23
Contributed: Tian Le, Jialiang, Andersen & Isaac, Kenrick

**Comment by ctianle** [comment]
Detail: Finishing up the sequence diagram by adding additional details and polishing it
Committed to repo: No
How does it affect success criteria: Helps to perfect and finalise the sequence diagram
Start Date: 21/10/23
End Date: 23/10/23
Contributed: Tian Le, Jialiang, Andersen & Isaac, Kenrick
