### ISSUE TITLE
2.4.1 Review Introduction Section in M2 Report

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#57]
1. Task Description: To review the Introduction section of M2 Report and make changes if necessary
2. Task Goals: To ensure that the Introduction section of the M2 Report is well written.
3. Success or completion criteria: The Introduction section of the M2 Report to be checked.
4. Allocated Time: 1 Hour
5. Start Date: 27/10/23
6. End Date: 28/10/23
7. Task Owner: Kenrick
8. Status: In Progress
9. Priority: Medium

**Comment by Krackern** [comment]
Detail: M2 report introduction section has been checked and vetted for submission
Committed to repo: No
How does it affect success criteria: Introduction section of the M2 report has been vetted and reviewed by the team. 
Start Date: 27/10/23
End Date: 27/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick
