### ISSUE TITLE
2.2.5 Review and Edit Component Diagram

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#60]
1. Task Description: The component diagram has to be reviewed by the team and changes will be made when necessary.
2. Task Goals: To ensure the component diagram is thoroughly vetted by the team.
3. Success or completion criteria: Component diagram has to be reviewed.
4. Allocated Time: 3 Hours 
5. Start Date: 17/10/23
6. End Date: 20/10/23
7. Task Owner: Kenrick
8. Status: Completed
9. Priority:  High

**Comment by frostsg** [comment]
-

**Comment by Krackern** [comment]
Detail: Clarified component diagrams with prof indriyani
Committed to repo: No
How does it affect success criteria: Helps us determine how we should structure our component diagram
Start Date: 20/10/23
End Date: 20/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick

Reason for overrun: Other projects and assignments to complete

**Comment by Krackern** [comment]
Detail: Clarified component diagrams with prof eric
Committed to repo: No
How does it affect success criteria: Helps us determine how we should structure our component diagram
Start Date: 24/10/23
End Date: 24/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick

Reason for overrun: Other projects and assignments to complete

**Comment by Krackern** [comment]
Detail: Component Diagram has been checked and vetted for submission
Committed to repo: No
How does it affect success criteria: Component diagram has been vetted and reviewed by the team.
Start Date: 27/10/23
End Date: 27/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick

Reason for overrun: Other projects and assignments to complete
