### ISSUE TITLE
2.4.2 Review Changes In Requirement Section

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#62]
1. Task Description: To review the Changes in Requirement section of the M2 report and make any necessary edits.
2. Task Goals: To ensure that the section is coherent and well-written.
3. Success or completion criteria: The Changes in Requirement section has been reviewed.
4. Allocated Time: 1 Hour
5. Start Date: 27/10/23
6. End Date: 28/10/23
7. Task Owner: Kenrick
8. Status: Completed
9. Priority: Medium

**Comment by Krackern** [comment]
Detail: M2 report requirement section has been checked and vetted for submission
Committed to repo: No
How does it affect success criteria: Requirement section of the M2 report has been vetted and reviewed by the team.
Start Date: 27/10/23
End Date: 27/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick
