### ISSUE TITLE
2.4.4 Review Updated Project Plan

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#64]
1. Task Description: To review the Updated Project plan section of the M2 report and make any necessary changes.
2. Task Goals: The section has to be coherent and well-written.
3. Success or completion criteria: The section's review has to be completed.
4. Allocated Time: 1 Hour
5. Start Date: 27/10/23
6. End Date: 28/10/23
7. Task Owner: Kenrick
8. Status: Completed
9. Priority: Medium

**Comment by Krackern** [comment]
Detail: Project Plan has been checked and vetted for submission
Committed to repo: No
How does it affect success criteria: Project Plan of the M2 report has been vetted and reviewed by the team.
Start Date: 27/10/23
End Date: 27/10/23
Contributed by: Jia Liang, Tian Le & Andersen, Isaac, Kenrick
