### ISSUE TITLE
3.1.1 Evaluate Use Case Diagrams & Descriptions

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#65]
1. Task Description: To evaluate use case diagram and descriptions based on feedback given from Milestone 2.
2. Task Goals: To ensure that the use case diagram and descriptions are accordingly to the client requirements if it is not.
3. Success or completion criteria: To ensure that the use case diagram and descriptions are reviewed and evaluated.
4. Allocated Time: 2 Hours
5. Start Date: 02/11/23
6. End Date: 03/11/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Not needed for m3
Committed to repo: No
How does it affect success criteria: Not required for M3.
Start Date: 6/11/2023
End Date: 6/11/2023
Contributed by Tian Le
