### ISSUE TITLE
3.1.2 Update Use Case Diagrams & Descriptions

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#66]
1. Task Description: To update the use case diagram and descriptions
2. Task Goals: To update the use case diagram and descriptions according to client requirements if it is not.
3. Success or completion criteria: Use case diagram and descriptions to be tweaked if necessary.
4. Allocated Time: 4 Hours 
5. Start Date: 02/11/23
6. End Date: 03/11/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Not needed for m3
Committed to repo: No
How does it affect success criteria: Not required for M3.
Start Date: 6/11/2023
End Date: 6/11/2023
Contributed by Tian Le
