### ISSUE TITLE
3.1.3 Evaluate Class Diagram

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#67]
1. Task Description: To evaluate the class diagram based on feedback given from M2
2. Task Goals: To ensure that the class diagram is understandable and according to use case requirements.
3. Success or completion criteria: The class diagram has to be reviewed thoroughly.
4. Allocated Time: 2 Hours
5. Start Date: 04/11/23
6. End Date: 05/11/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: High

**Comment by ctianle** [comment]
Detail: Finish evaluating class diagram and adjusted criteria as for architectural design. 
Committed to repo: No
How does it affect success criteria: No feedback are supposed to be given from M2 regarding change of class diagram.
Start Date: 8/11/23
End Date: 8/11/23
Contributed by Jia Liang, Tian Le, Isaac, Kenrick & Andersen
