### ISSUE TITLE
3.1.4 Update Class Diagram

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#68]
1. Task Description: To update the class diagram based on feedback given from M2 report.
2. Task Goals: To ensure that the class diagram is thoroughly updated and understandable by programmers.
3. Success or completion criteria: Class diagram has to be edited based on the feedback from M2 report.
4. Allocated Time: 5 Hours
5. Start Date: 04/11/23
6. End Date: 05/11/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: High

**Comment by Littlesens** [comment]
1. Detail: update the employee entity on the class diagram based on feedback given from M2 report.
2. Committed to repo: No
3. How does it affect success criteria: Helps to make our entity class clearer and more detailed
4. Start Date: 07/11/23
5. End Date: 07/11/23

Contributed by Jia Liang, Tian Le & Andersen
