### ISSUE TITLE
3.2.1.1 Create Architectural Design

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#69]
1. Task Description: To create an architectural design for the system
2. Task Goals: To apply architectural design concepts learned in the lesson.
3. Success or completion criteria: A Architectural design has to be created.
4. Allocated Time: 2 Hours
5. Start Date: 05/11/23
6. End Date: 06/11/23
7. Task Owner: Kenrick
8. Status: Completed.
9. Priority: Medium

**Comment by Krackern** [comment]
Detail: Created a draft of the architectural design for the system
Committed to repo: No
How does it affect success criteria Allows us to check with the Professor if we are on the right track for the design
Start Date: 05/11/23
End Date: 05/11/23
Contributed by Jia Liang, Tian Le, Isaac, Kenrick & Andersen

**Comment by ctianle** [comment]
Detail: Finished architectural design for the system.
Committed to repo: No
How does it affect success criteria: Correctly identify the architectural design we should adopt.
Start Date: 8/11/23
End Date: 8/11/23
Contributed by Jia Liang, Tian Le, Isaac, Kenrick & Andersen
