### ISSUE TITLE
3.2.2.1 Review Design Patterns

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#70]
1. Task Description: To review design patterns for the system.
2. Task Goals: To select suitable design patterns for the system.
3. Success or completion criteria: A design pattern has to be selected along with its justification for it.
4. Allocated Time: 2 Hours
5. Start Date: 06/11/23
6. End Date: 07/11/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: Medium

**Comment by ctianle** [comment]
Detail: Identified design patterns required.
Committed to repo: No
How does it affect success criteria: Successfully identified the detailed pattern to continue progressing.
Start Date: 1111/2023
End Date: 11/11/2023
Contributed by Tian Le
