### ISSUE TITLE
3.2.2.2 Apply Design Patterns into Class Diagram

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#71]
1. Task Description: To apply design patterns into the existing class diagram
2. Task Goals: To change the class diagram with design pattern that is selected previously.
3. Success or completion criteria: The class diagram should follow the selected design pattern. 
4. Allocated Time: 6 Hours
5. Start Date: 07/11/23
6. End Date: 12/11/23
7. Task Owner: Tian Le
8. Status: Completed
9. Priority: Medium

**Comment by ctianle** [comment]
Detail: Applied design pattern into selected parts of class diagram
Committed to repo: No
How does it affect success criteria: allows for class diagram visual regarding the part we are implementing design patterns.
Start Date: 11/11/2023
End Date: 11/11/2023
Contributed by Tian Le
