### ISSUE TITLE
3.3.2 Design Black Box Testcases

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#72]
1. Task Description: Design black box test cases
2. Task Goals: To design the black box test cases for our system.
3. Success or completion criteria: Black box test cases to be created.
4. Allocated Time: 5 Hours
5. Start Date: 12/11/23
6. End Date: 15/11/23
7. Task Owner: Andersen
8. Status: Completed
9. Priority: Medium

**Comment by Littlesens** [comment]
Detail: Selected one prominent method related to my use cases and designed the decision table black box testing for it
Committed to repo: No
How does it affect success criteria: fulfills the criteria in the Black Box Testing of the report
Start Date: 15/11/23
End Date: 15/11/23
Contributed by: Isaac

**Comment by ctianle** [comment]
Detail: Completed black box test case design by adding and making the correct details.
Committed to repo: No
How does it affect success criteria: Complete the black box testcase.
Start Date: 15/11/23
End Date: 15/11/23
Contributed by: Tian Le
