### ISSUE TITLE
3.4.4 Design White Box Testcases

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#73]
1. Task Description: To design white box test cases for the system
2. Task Goals: To apply white box testing concepts into the project
3. Success or completion criteria: White box test cases has to be completed.
4. Allocated Time: 5 Hours
5. Start Date: 15/11/23
6. End Date: 17/11/23
7. Task Owner: Isaac
8. Status: Completed
9. Priority: Medium

**Comment by frostsg** [comment]
i. Detail: Selected one prominent method to apply white box testing.
ii. Committed to repo: No
iii. How does it affect success criteria: We are now able to start on designing the testcases.
iv. Start Date: 08/11/23
v. End Date: 08/11/23

Contributed by: Isaac, Tian Le

**Comment by Krackern** [comment]
i. Detail: Added Pseudocode, Control Flow Graph, Cyclomatic complexity, Basis Paths and Test Cases (to consult with Professor Indriyati if it is correct)
ii. Committed to repo: No
iii. How does it affect success criteria: We are able to further refine our White Box Testcases after consultation
iv. Start Date: 12/11/23
v. End Date: 13/11/23

Contributed by: Kenrick

**Comment by ctianle** [comment]
i. Detail: Revised CFG, Cyclomatic Complexity and Test Case. 
ii. Committed to repo: No
iii. How does it affect success criteria: Completion helps to finish white box testcases.
iv. Start Date: 15/11/23
v. End Date: 15/11/23

Contributed by: Kenrick
