### ISSUE TITLE
3.5.1 Design User Interface Mockups

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#74]
1. Task Description: To design the user interface mockups via sketch to conceptualise it
2. Task Goals: To come out with a basic sketch of a user interface for the system
3. Success or completion criteria: A basic user interface sketch must be drawn.
4. Allocated Time: 5 Hours
5. Start Date: 17/11/23
6. End Date: 19/11/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: Low

**Comment by ctianle** [comment]
Detail: Came up with mockups via sketches
Committed to repo: No
How does it affect success criteria: Helps to conceptualise the User Interface for Wireframe.
Start Date: 17/11/23
End Date: 19/11/23
Contributed by JiaLiang.
