### ISSUE TITLE
3.5.2 Design High Fidelity Wireframe

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#75]
1. Task Description: To design wireframes of the user interface.
2. Task Goals: To show a high-fidelity design of the system.
3. Success or completion criteria: To come out with high fidelity wireframe for demonstration 
4. Allocated Time: 8 Hours
5. Start Date: 19/11/23
6. End Date: 21/11/23
7. Task Owner: Jia Liang
8. Status: Completed
9. Priority: Low

**Comment by tjl081** [comment]
i. Detail: created all wireframes, written into the report
ii. Committed to repo: No
iii. How does it affect success criteria: MS presenter can use write-up in report as guide for presentation
iv. Start Date: 16/11/23
v. End Date: 20/11/23

**Comment by tjl081** [comment]
i. Detail: wireframes finalised and M3 video presentation completed based off wireframes
ii. Committed to repo: No
iii. How does it affect success criteria: MS presenter can use write-up in report as guide for presentation
iv. Start Date: 16/11/23
v. End Date: 21/11/23
