### ISSUE TITLE
M1: Setup an Appointment With the Client

### ISSUE THREAD

**Issue by frostsg** [frostsg/inf2001-p11-2#8]
1. Task Description: Setup appointment to understand the requirements of the client
2. Task Goals: To communicate with the client to arrange an appointment
3. Success or completion criteria: Confirmed the date and time for the client meeting
4. Allocated Time: 10 Minutes
5. Start Date: 31/08/23
6. End Date: 31/08/23
7. Task Owner: Kenrick
8. Status: Completed
9. Priority: High

**Comment by tjl081** [comment]
1. Detail: Setup an Appointment With the Client
2. Committed to repo: No
3. How does it affect success criteria: Allows the team to ask questions regarding the project brief to the client directly, for hashing out goals and expectations for the project
4. Start Date: 31/08/23
5. End Date: 31/08/23
